### ISSUE TITLE
hipercam rtplot all black

### ISSUE THREAD

**Issue by paulkerry1** [WarwickAstro/trm-pgplot#1]
Using the latest "Commits on Nov 7, 2019", rtplot of a local hipercam file displays all frames from the 5x ccd images as totally black. hplot on a grabbed file from the the same run files works fine.

**Comment by trmrsh** [comment]
can't replicate this Paul. Could you run "rtplot list \\" (once you have set up an example where it displays black), tell me the exact run and cut-and-paste me the arguments that come back from rtplot

**Comment by paulkerry1** [comment]
Using hipercam data run0014.fits from 2018_06_10

Here's the output from rtplot list \

rtplot` list \

? 

rtplot
source = hl
device = 1/xs
width = 0.0
height = 0.0
run - run name [run0014]: 
run = run0014
first - first frame to plot [1]: 
first = 1
twait = 1.0
tmax = 10.0
ccd - CCD(s) to plot [0 for all] [0]: 
ccd = 0
nx - number of panels in X [3]: 
nx = 3
pause = 0.0
plotall = False
bias - bias frame ['none' to ignore] [none]: 
bias = none
defect - defect file ['none' to ignore] [none]: 
defect = none
setup - display current hdriver window settings [False]: 
setup = False
msub - subtract median from each window? [False]: 
msub = False
iset - set intensity a(utomatically), d(irectly) or with p(ercentiles)? [p]: 
iset = p
plo - lower intensity limit percentile [1.0]: 
plo = 1.0
phi - upper intensity limit percentile [99.0]: 
phi = 99.0
xlo - left-hand X value [-50.0]: 
xlo = -50.0
xhi - right-hand X value [2099.0]: 
xhi = 2099.0
ylo - lower Y value [-8.0]: 
ylo = -8.0
yhi - upper Y value [1033.0]: 
yhi = 1033.0
1, utc = 2018-06-11 03:35:45.550, , ccd 2: 1126.0, 1387.0, exp: 1.2138, ccd 3: 1117.0, 1595.0, exp: 1.2138, ccd 4: 1030.0, 1560.0, exp: 1.2138
2, utc = 2018-06-11 03:35:46.771, ccd 1: 866.0, 1244.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1059.0, 1594.0, exp: 1.2138, ccd 5: 1563.0, 2185.0, exp: 1.2138
3, utc = 2018-06-11 03:35:47.993, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1057.0, 1593.0, exp: 1.2138
4, utc = 2018-06-11 03:35:49.215, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1059.0, 1594.0, exp: 1.2138, ccd 5: 1629.0, 2254.0, exp: 1.2138
5, utc = 2018-06-11 03:35:50.436, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1593.0, exp: 1.2138
6, utc = 2018-06-11 03:35:51.658, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1059.0, 1594.0, exp: 1.2138, ccd 5: 1630.0, 2254.0, exp: 1.2138
7, utc = 2018-06-11 03:35:52.879, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1592.0, exp: 1.2138
8, utc = 2018-06-11 03:35:54.101, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1131.0, 1612.0, exp: 1.2138, ccd 4: 1059.0, 1594.0, exp: 1.2138, ccd 5: 1630.0, 2253.0, exp: 1.2138
9, utc = 2018-06-11 03:35:55.322, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1593.0, exp: 1.2138
10, utc = 2018-06-11 03:35:56.544, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1059.0, 1594.0, exp: 1.2138, ccd 5: 1629.0, 2254.0, exp: 1.2138
11, utc = 2018-06-11 03:35:57.766, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1594.0, exp: 1.2138
12, utc = 2018-06-11 03:35:58.987, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1131.0, 1613.0, exp: 1.2138, ccd 4: 1059.0, 1596.0, exp: 1.2138, ccd 5: 1630.0, 2255.0, exp: 1.2138
13, utc = 2018-06-11 03:36:00.209, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1595.0, exp: 1.2138
14, utc = 2018-06-11 03:36:01.430, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1059.0, 1595.0, exp: 1.2138, ccd 5: 1629.0, 2255.0, exp: 1.2138
15, utc = 2018-06-11 03:36:02.652, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1594.0, exp: 1.2138
16, utc = 2018-06-11 03:36:03.874, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1059.0, 1594.0, exp: 1.2138, ccd 5: 1629.0, 2254.0, exp: 1.2138
17, utc = 2018-06-11 03:36:05.095, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1592.0, exp: 1.2138
18, utc = 2018-06-11 03:36:06.317, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1131.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1594.0, exp: 1.2138, ccd 5: 1628.0, 2253.0, exp: 1.2138
19, utc = 2018-06-11 03:36:07.538, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1057.0, 1592.3, exp: 1.2138
20, utc = 2018-06-11 03:36:08.760, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1135.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1594.0, exp: 1.2138, ccd 5: 1627.0, 2251.0, exp: 1.2138
21, utc = 2018-06-11 03:36:09.981, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1057.7, 1593.0, exp: 1.2138
22, utc = 2018-06-11 03:36:11.203, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1594.0, exp: 1.2138, ccd 5: 1627.0, 2251.0, exp: 1.2138
23, utc = 2018-06-11 03:36:12.425, , ccd 2: 1135.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1616.0, exp: 1.2138, ccd 4: 1057.0, 1597.0, exp: 1.2138
24, utc = 2018-06-11 03:36:13.646, ccd 1: 868.0, 1248.0, exp: 1.2138, ccd 2: 1134.0, 1402.0, exp: 1.2138, ccd 3: 1130.0, 1615.0, exp: 1.2138, ccd 4: 1059.0, 1602.0, exp: 1.2138, ccd 5: 1633.0, 2256.0, exp: 1.2138
25, utc = 2018-06-11 03:36:14.868, , ccd 2: 1134.0, 1400.0, exp: 1.2138, ccd 3: 1130.0, 1614.0, exp: 1.2138, ccd 4: 1058.0, 1596.0, exp: 1.2138
26, utc = 2018-06-11 03:36:16.089, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1135.0, 1400.0, exp: 1.2138, ccd 3: 1130.0, 1614.0, exp: 1.2138, ccd 4: 1058.0, 1597.0, exp: 1.2138, ccd 5: 1627.0, 2255.3, exp: 1.2138
27, utc = 2018-06-11 03:36:17.311, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1614.0, exp: 1.2138, ccd 4: 1058.0, 1596.0, exp: 1.2138
28, utc = 2018-06-11 03:36:18.532, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1135.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1596.0, exp: 1.2138, ccd 5: 1627.0, 2253.0, exp: 1.2138
29, utc = 2018-06-11 03:36:19.754, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1594.0, exp: 1.2138
30, utc = 2018-06-11 03:36:20.976, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1135.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1596.0, exp: 1.2138, ccd 5: 1626.0, 2251.0, exp: 1.2138
31, utc = 2018-06-11 03:36:22.197, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1594.0, exp: 1.2138
32, utc = 2018-06-11 03:36:23.419, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1135.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1595.0, exp: 1.2138, ccd 5: 1627.0, 2252.0, exp: 1.2138
33, utc = 2018-06-11 03:36:24.640, , ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1594.0, exp: 1.2138
34, utc = 2018-06-11 03:36:25.862, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1058.0, 1594.0, exp: 1.2138, ccd 5: 1626.7, 2253.0, exp: 1.2138
35, utc = 2018-06-11 03:36:27.083, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1593.0, exp: 1.2138
36, utc = 2018-06-11 03:36:28.305, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1596.0, exp: 1.2138, ccd 5: 1625.0, 2252.0, exp: 1.2138
37, utc = 2018-06-11 03:36:29.527, , ccd 2: 1134.0, 1400.0, exp: 1.2138, ccd 3: 1130.0, 1614.0, exp: 1.2138, ccd 4: 1057.0, 1597.0, exp: 1.2138
38, utc = 2018-06-11 03:36:30.748, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1058.0, 1596.0, exp: 1.2138, ccd 5: 1626.0, 2253.0, exp: 1.2138
39, utc = 2018-06-11 03:36:31.970, , ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1595.0, exp: 1.2138
40, utc = 2018-06-11 03:36:33.191, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1403.0, exp: 1.2138, ccd 3: 1130.0, 1616.0, exp: 1.2138, ccd 4: 1058.0, 1603.0, exp: 1.2138, ccd 5: 1626.0, 2255.0, exp: 1.2138
41, utc = 2018-06-11 03:36:34.413, , ccd 2: 1134.0, 1403.0, exp: 1.2138, ccd 3: 1130.0, 1616.0, exp: 1.2138, ccd 4: 1057.0, 1601.0, exp: 1.2138
42, utc = 2018-06-11 03:36:35.635, ccd 1: 868.0, 1248.0, exp: 1.2138, ccd 2: 1134.0, 1401.0, exp: 1.2138, ccd 3: 1131.0, 1615.0, exp: 1.2138, ccd 4: 1058.0, 1599.0, exp: 1.2138, ccd 5: 1625.0, 2254.0, exp: 1.2138
43, utc = 2018-06-11 03:36:36.856, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1593.0, exp: 1.2138
44, utc = 2018-06-11 03:36:38.078, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1057.0, 1593.0, exp: 1.2138, ccd 5: 1622.0, 2248.0, exp: 1.2138
45, utc = 2018-06-11 03:36:39.299, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.3, exp: 1.2138, ccd 4: 1056.0, 1593.0, exp: 1.2138
46, utc = 2018-06-11 03:36:40.521, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1057.0, 1593.0, exp: 1.2138, ccd 5: 1621.0, 2246.0, exp: 1.2138
47, utc = 2018-06-11 03:36:41.742, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1129.0, 1612.0, exp: 1.2138, ccd 4: 1056.0, 1592.0, exp: 1.2138
48, utc = 2018-06-11 03:36:42.964, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1057.0, 1593.0, exp: 1.2138, ccd 5: 1618.0, 2242.0, exp: 1.2138
49, utc = 2018-06-11 03:36:44.186, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1129.0, 1612.0, exp: 1.2138, ccd 4: 1056.0, 1592.0, exp: 1.2138
50, utc = 2018-06-11 03:36:45.407, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1056.0, 1593.0, exp: 1.2138, ccd 5: 1615.0, 2240.0, exp: 1.2138
51, utc = 2018-06-11 03:36:46.629, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1129.0, 1612.0, exp: 1.2138, ccd 4: 1055.0, 1591.0, exp: 1.2138
52, utc = 2018-06-11 03:36:47.850, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1056.0, 1591.0, exp: 1.2138, ccd 5: 1613.0, 2238.0, exp: 1.2138
53, utc = 2018-06-11 03:36:49.072, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1129.0, 1612.0, exp: 1.2138, ccd 4: 1054.0, 1590.0, exp: 1.2138
54, utc = 2018-06-11 03:36:50.293, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1611.0, exp: 1.2138, ccd 4: 1055.0, 1590.0, exp: 1.2138, ccd 5: 1612.0, 2236.0, exp: 1.2138
55, utc = 2018-06-11 03:36:51.515, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1129.0, 1611.0, exp: 1.2138, ccd 4: 1054.0, 1588.0, exp: 1.2138
56, utc = 2018-06-11 03:36:52.737, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1135.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1611.0, exp: 1.2138, ccd 4: 1055.0, 1590.0, exp: 1.2138, ccd 5: 1611.0, 2235.0, exp: 1.2138
57, utc = 2018-06-11 03:36:53.958, , ccd 2: 1134.0, 1396.0, exp: 1.2138, ccd 3: 1129.0, 1611.0, exp: 1.2138, ccd 4: 1054.0, 1588.0, exp: 1.2138
58, utc = 2018-06-11 03:36:55.180, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1130.0, 1611.0, exp: 1.2138, ccd 4: 1055.0, 1588.0, exp: 1.2138, ccd 5: 1610.0, 2233.0, exp: 1.2138
59, utc = 2018-06-11 03:36:56.401, , ccd 2: 1134.0, 1396.0, exp: 1.2138, ccd 3: 1129.0, 1611.0, exp: 1.2138, ccd 4: 1054.0, 1587.0, exp: 1.2138
60, utc = 2018-06-11 03:36:57.623, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1129.0, 1611.0, exp: 1.2138, ccd 4: 1055.0, 1588.0, exp: 1.2138, ccd 5: 1609.0, 2232.0, exp: 1.2138
61, utc = 2018-06-11 03:36:58.844, , ccd 2: 1134.0, 1397.0, exp: 1.2138, ccd 3: 1129.0, 1611.0, exp: 1.2138, ccd 4: 1054.0, 1589.0, exp: 1.2138
62, utc = 2018-06-11 03:37:00.066, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1055.0, 1590.0, exp: 1.2138, ccd 5: 1610.0, 2234.0, exp: 1.2138
63, utc = 2018-06-11 03:37:01.288, , ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1129.0, 1613.0, exp: 1.2138, ccd 4: 1054.0, 1592.0, exp: 1.2138
64, utc = 2018-06-11 03:37:02.509, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1612.0, exp: 1.2138, ccd 4: 1055.0, 1593.0, exp: 1.2138, ccd 5: 1609.0, 2235.0, exp: 1.2138
65, utc = 2018-06-11 03:37:03.731, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1129.0, 1612.0, exp: 1.2138, ccd 4: 1054.0, 1590.0, exp: 1.2138
66, utc = 2018-06-11 03:37:04.952, ccd 1: 868.0, 1247.0, exp: 1.2138, ccd 2: 1134.0, 1400.0, exp: 1.2138, ccd 3: 1130.0, 1613.0, exp: 1.2138, ccd 4: 1055.0, 1593.0, exp: 1.2138, ccd 5: 1608.0, 2234.0, exp: 1.2138
67, utc = 2018-06-11 03:37:06.174, , ccd 2: 1134.0, 1401.0, exp: 1.2138, ccd 3: 1129.0, 1616.0, exp: 1.2138, ccd 4: 1054.0, 1596.0, exp: 1.2138
68, utc = 2018-06-11 03:37:07.396, ccd 1: 868.0, 1248.0, exp: 1.2138, ccd 2: 1134.0, 1400.0, exp: 1.2138, ccd 3: 1130.0, 1614.0, exp: 1.2138, ccd 4: 1055.0, 1595.0, exp: 1.2138, ccd 5: 1608.0, 2237.0, exp: 1.2138
69, utc = 2018-06-11 03:37:08.617, , ccd 2: 1134.0, 1417.0, exp: 1.2138, ccd 3: 1130.0, 1635.0, exp: 1.2138, ccd 4: 1054.0, 1602.0, exp: 1.2138
70, utc = 2018-06-11 03:37:09.839, ccd 1: 868.0, 1248.0, exp: 1.2138, ccd 2: 1134.0, 1401.0, exp: 1.2138, ccd 3: 1130.0, 1621.0, exp: 1.2138, ccd 4: 1055.0, 1589.0, exp: 1.2138, ccd 5: 1607.0, 2248.0, exp: 1.2138
71, utc = 2018-06-11 03:37:11.060, , ccd 2: 1134.0, 1402.0, exp: 1.2138, ccd 3: 1130.0, 1621.0, exp: 1.2138, ccd 4: 1054.0, 1588.0, exp: 1.2138
72, utc = 2018-06-11 03:37:12.282, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1399.0, exp: 1.2138, ccd 3: 1130.0, 1617.0, exp: 1.2138, ccd 4: 1054.0, 1587.0, exp: 1.2138, ccd 5: 1606.0, 2233.0, exp: 1.2138
73, utc = 2018-06-11 03:37:13.503, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1129.0, 1615.0, exp: 1.2138, ccd 4: 1053.0, 1586.0, exp: 1.2138
74, utc = 2018-06-11 03:37:14.725, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1615.0, exp: 1.2138, ccd 4: 1054.0, 1586.0, exp: 1.2138, ccd 5: 1604.0, 2229.0, exp: 1.2138
75, utc = 2018-06-11 03:37:15.947, , ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1129.0, 1615.0, exp: 1.2138, ccd 4: 1053.0, 1585.0, exp: 1.2138
76, utc = 2018-06-11 03:37:17.168, ccd 1: 868.0, 1246.0, exp: 1.2138, ccd 2: 1134.0, 1398.0, exp: 1.2138, ccd 3: 1130.0, 1615.0, exp: 1.2138, ccd 4: 1054.0, 1586.0, exp: 1.2138, ccd 5: 1604.0, 2228.0, exp: 1.2138
henderror raised
 Press RETURN for next page:

**Comment by trmrsh** [comment]
Hmm, that still seems to work for me, albeit several of the quadrants of each CCD come out black, but not all. (msub=yes fixes this issue as well -- you should give that a go). Otherwise it's very puzzling as the plot level outputs are identical and it just sends off the data to pgplot. Does it do this on every run for you?

**Comment by paulkerry1** [comment]
Further info - I've tried re-installing trm-pgplot again: something must be different with the pip3 install as I expect the install to fail if PGPLOT_DIR is not set before running the install.
If I set PGPLOT_DIR and install, then rtplot fails with...
ImportError: /usr/local/lib/libpgplot.so: undefined symbol: png_set_longjmp_fn

**Comment by trmrsh** [comment]
That's odd. png_set_longjmp_fn is not a function I have ever used and sounds low level. I have actually given up installing the PNG drivers with PGPLOT. Perhaps it's fixable, but I had some problems with them and gave up; perhaps this is part of the same thing? By the way, are you saying that the pip3 install of PGPLOT does not mind if PGPLOT_DIR is set or not?

**Comment by trmrsh** [comment]
one thing to try is to set "device=/xs" with "hplot" -- it will direct the plot to pgplot rather than matplotlib. sorry if you already tried. "device=/mpl" will get you back to matplotlib.

**Comment by paulkerry1** [comment]
It is something to do with png/pgplot, and yes to the setting of PGPLOT_DIR and pip3.

Without setting "export PGPLOT_DIR=/usr/local/pgplot-5.2.2", pip3 allows me to install and all the ccd windows are black for every hipercam and ultracam file I have tested.

If I re-add 'png' to the "libraries" line in setup.py and "export PGPLOT_DIR=/usr/local/pgplot-5.2.2" and reinstall again, then I do not get the "undefined symbol" error and everything works perfectly: all hipercam and ultracam files I have tested display correctly. I cannot remove png from the pgplot setup as this is used by non-hipercam users.

**Comment by trmrsh** [comment]
groan, PGPLOT is such a pain. I will see if I can manage to get the PNG drivers working at this end. I might be able to add the png library back in in any case without affecting my own setup. I was probably trying not to link to libraries that were not necessary (for me) as every extra library is an extra chance for there to be problems if it can't be found.

**Comment by trmrsh** [comment]
OK, it seems happy with png added back in even though I don't use it. I also added "z" because I seem to remember that being needed although you don't mention it. Let me know one way or the other, and I will push the fixes to trm-pgplot. I have fixed the issue with PGPLOT_DIR I think.

**Comment by paulkerry1** [comment]
I did not add 'z' to the libraries line in setup.py, but having done so and reinstalled, everything works fine.

**Comment by paulkerry1** [comment]
pip3 install is now working correctly with PGPLOT_DIR and all plotting is working now with your fixes Tom
